---

- name: packages | add dependencies
  apt:
    name:
      - gnupg2
      - apt-transport-https
      - ca-certificates
      - software-properties-common
    update_cache: true
    state: present

- name: packages | add ppa repo
  apt_repository:
    repo: ppa:gluster/glusterfs-{{ gluster_version }}
    filename: glusterfs
    state: present

- name: packages | install glusterfs client and server
  apt:
    name:
      - glusterfs-client
      - glusterfs-server
    state: present

- name: packages | ensure glusterd is enabled
  service:
    name: glusterd
    enabled: yes
