---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint

platforms:
  - name: focal
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    command: "/lib/systemd/systemd"
    privileged: true
    pre_build_image: true

  - name: bionic
    image: geerlingguy/docker-ubuntu1804-ansible:latest
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    command: "/lib/systemd/systemd"
    privileged: true
    pre_build_image: true

  - name: xenial
    image: geerlingguy/docker-ubuntu1604-ansible:latest
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    command: "/lib/systemd/systemd"
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        gluster_bricks:
          - brick_dir: /gluster/brick1
            mount_dir:
            brick_name: brick1
            brick_replicas: 3

verifier:
  name: ansible
